
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-app-1
stratagyType: RollingUpdate
spec:
  replicas: 5
  selector:
    matchLabels:
      app: efs-app-1
  template:
    metadata:
      labels:
        app: efs-app-1
    spec:
      #serviceAccountName: app-sa  # Optional, if you created a ServiceAccount
      containers:
        - name: app-container
          image: nginx  # Replace with your actual app image
         # volumeMounts:
            #- name: efs-storage
           #   mountPath: /mnt/data  # Path inside the container
     #Volumes:
        #- name: efs-storage
         # persistentVolumeClaim:
            #claimName: efs-pvc
